# Conda Environment file to install ETA "fast".
# Run:
# > conda env create --name ETA -f conda_ETA_env.yml
name: ETA
dependencies:
  - python=3
  - pip
  - cffi
  - llvmlite
  - aiohttp
  - astunparse
  - numpy
  - scipy
  - numba
  - matplotlib
  - bokeh
  - pandas  
  - pip:
    - etabackend
    - lmfit
