# Conda Environment file to install ETA "fast".
# Run:
# > conda env create --name ETA -f conda_ETA_env.yml
name: ETA
channels:
  - conda-forge
  - default
dependencies:
  - python >= 3.9
  - pip
  - cffi
  - llvmlite
  - aiohttp
  - astunparse
  - numpy>=2.0.0
  - scipy
  - numba
  - matplotlib
  - bokeh
  - pandas  
  - lmfit
  - pip:
    - etabackend